name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '12' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: "yarn prettier:check"
      - run: yarn test
